version: "3"

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ./dbdata:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: ghcr.io/shockzinfinity/wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./dataredis:/data

  wordpress-nginx:
    depends_on:
      - wordpress
    container_name: wordpress-nginx
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=wordpress.shockz.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=wordpress.shockz.io
      - LETSCRYPT_EMAIL=shockzinfinity@gmail.com
    restart: unless-stopped
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d

volumes:
  wordpress:
  dbdata:
  nginx-conf:
  dataredis:

networks:
  default:
    external:
      name: nginx-proxy
